#!/usr/bin/env bash
# yolo: dangerously skip permissions alias.
alias yolo="claude --dangerously-skip-permissions"

# plist: list all available commands.
plist() {
  local ver header
  ver="$(_pwork_version)"
  header="parallel-work ${ver} commands"
  echo "$header"
  # ${#var} gives the string length; printf repeats '=' that many times
  printf '%0.s=' $(seq 1 ${#header})
  echo ""
  echo ""
  echo "  p-init URL [PATH]    Set up a new workspace from a repo URL"
  echo "    example:  p-init git@github.com:org/repo.git"
  echo "    example:  p-init git@github.com:org/repo.git ~/pwork-repos/repo"
  echo "    flags:    --clones N  --branch NAME  --sync-cmd \"...\""
  echo ""
  echo "  p<N>                 cd into clone pN of the current workspace"
  echo "    example:  p3"
  echo ""
  echo "  pw [N]               List all workspaces, or cd to workspace N"
  echo "    example:  pw            (list workspaces)"
  echo "    example:  pw 2          (cd to workspace 2)"
  echo "    flags:    --add PATH    (register an existing workspace)"
  echo ""
  echo "  p-sync               Pull + sync dependencies across all clones"
  echo "    example:  p-sync"
  echo ""
  echo "  p-status             Show branch, last commit, dirty/clean, and PR status"
  echo "    example:  p-status"
  echo ""
  echo "  p-branches           Show which branch each clone is on + PR/merge status"
  echo "    example:  p-branches"
  echo ""
  echo "  p-new                Create the next pN clone in the current workspace"
  echo "    example:  p-new"
  echo ""
  echo "  p-setup              Apply statusline + clone config to all clones"
  echo "    example:  p-setup"
  echo ""
  echo "  p-clean [pN]         Recycle clones whose PR has been merged"
  echo "    example:  p-clean           (all clones)"
  echo "    example:  p-clean p2        (just p2)"
  echo "    flags:    --dry-run"
  echo ""
  echo "  p-update             Update parallel-work to the latest version"
  echo "    example:  p-update"
  echo ""
  echo "  p-version            Show installed version and git SHA"
  echo "    example:  p-version"
  echo ""
  echo "  yolo                 Run claude --dangerously-skip-permissions"
  echo "    example:  yolo"
  echo ""
  echo "  plist                Show this help message"
  echo "    example:  plist"
}
